apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=822233328858.dkr.ecr.eu-north-1.amazonaws.com/my-app
    argocd-image-updater.argoproj.io/myapp.update-strategy: semver
    argocd-image-updater.argoproj.io/git-ssh-key-secret: repo-github-creds
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ViolinCake/k8s.git
    targetRevision: main
    kustomize: {}
    path: . # the dir within your repo that contains Kubernetes manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true